Repository canada-ca/systeme-conception, pull requests merged in 2023-03, with the labels that each got.

#119 Update _config.yml
  .gitignore
  Gemfile
  Gemfile.lock
  _config.dev.yml
  _config.preview.yml
  _config.yml
  netlify.toml
Labels: bug

#123 Update patterns-01-fr.json
  _config.preview.yml
  ajax/patterns-01-fr.json
Labels: bug

#124 Move page-acceuil-FR.html
  page-accueil-FR.html
Labels: wontfix

#122 Create retroaction/index.md
  retroaction/acces.md
  retroaction/ameliorer.md
  retroaction/communiquer.md
  retroaction/decider.md
  retroaction/etude-cas-ingredients.md
  retroaction/fonctionnement.md
  retroaction/images/case-study-content-thumbnail.jpg
  retroaction/images/description-fr.jpg
  retroaction/images/feedback-tagging-template.xlsx
  retroaction/images/feedback-viewer.png
  retroaction/images/footer-feedback-fr.png
  retroaction/images/page-feedback.png
  retroaction/images/templates-sharing-data.pptx
  retroaction/images/templates-sharing-tss-data.pptx
  retroaction/images/thank-you-fr.jpg
  retroaction/index.md
  retroaction/methodes.md
  retroaction/quand.md
  retroaction/soutien.md
Labels: documentation
